#!/usr/bin/env python3

import argparse
import pathlib

from pygrue import app


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="roll-for-vn",
        description="Dating sim not included",
    )
    parser.add_argument("-w", "--websocket",
                        default="websocket.json",
                        type=pathlib.Path,
    )
    args = parser.parse_args()
    app.VNApp(args.websocket)
